#!/usr/bin/env bash

## Simple script to remind me how to properly merge to master

BRANCH_NAME=$1

if [ -z "${BRANCH_NAME}" ]; then
  BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
fi

if [ "${BRANCH_NAME}" == "master" ]; then echo -e "\033[1;31mYou can't merge master on to master\033[0m"; exit; fi

echo -e "\033[32mHere we go\033[0m"
echo -e "\033[32mAll about that rebase\033[0m"
echo "git checkout master"
echo "git pull origin master"
echo "git checkout ${BRANCH_NAME}"
echo "git rebase master"
echo "git push -f origin ${BRANCH_NAME}"

echo -e "\n\033[93mTime to shipit\033[0m"
echo "git checkout master"
echo "git merge --ff-only ${BRANCH_NAME}"
echo "git push origin master"

echo -e "\n\033[35mCleanliness is next to godliness\033[0m"
echo "gbr ${BRANCH_NAME}"
echo "  or"
echo "git push origin :${BRANCH_NAME}"
echo "git branch -D ${BRANCH_NAME}"

