#!/bin/bash



if [ "$1" == "" ]
then
 nic=`/sbin/ifconfig | grep eth | awk '{print $1}'`
else
 nic=$1
fi

host=`/bin/hostname`
osrel=`perl -pe "s/\D//g" /etc/redhat\-release`

main()
{
	#build network config
	echo -e "Creating the network configs.\n"
	setnetconfig
	
	#back up resolv.conf
	echo -e "Backing up.\n"
	cp /etc/resolv.conf /etc/resolv.conf.bak

	#bounce network
	echo -e "Restarting the network.\n"
	service network restart

	#restore resolv.conf
	echo -e "Restoring resolv.conf.\n"
	cp /etc/resolv.conf.bak /etc/resolv.conf

}

setnetconfig()
{
	echo -e "DEVICE=$nic\nBOOTPROTO=dhcp\nDHCP_HOSTNAME=$host\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-$nic
}

main
