#!/bin/bash

DHCP_CONFIG="/Library/Preferences/VMware Fusion/vmnet8/dhcpd.conf"
#netmask=`awk '/subnet/,/\}/' "${DHCP_CONFIG}" | grep subnet | awk '{print $4}'`

uniq_ip () {
  subnet=`awk '/subnet/,/\}/' "${DHCP_CONFIG}" | grep subnet | awk '{print $2}' | cut -d. -f1,2,3`
  min=`awk '/subnet/,/\}/' "${DHCP_CONFIG}" | grep range | awk '{print $2}' | cut -d. -f4`
  max=`awk '/subnet/,/\}/' "${DHCP_CONFIG}" | grep range | awk '{print $3}' | cut -d. -f4 | cut -d\; -f1`
  diff=$((max-min+1));
  uniq=false
  uniqoctet=$(( min + RANDOM%diff ))
  while [[ ! ${uniq} ]];do
    if `grep "${subnet}.${uniqoctet}" ${DHCP_CONIG}`;then
      uniq=true
    else
      uniq=false
      uniqoctet=$(( min + RANDOM%diff ))
    fi
  done

  echo "$subnet.$uniqoctet"
}

ip=$(uniq_ip)
